# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Netlify workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm i

    - run: CI=false npm run build --if-present

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
        #run: echo "Tests incoming"

        # - name: Codecov
        #   uses: codecov/codecov-action@v2.1.0

    - name: Netlify Deploy
      #uses: jsmrcaga/action-netlify-deploy@v2.0.0

      env:
        NETLIFY_AUTH_TOKEN: nfp_xvZE12EBCNuLVZFSjc9iSFDRf6WCHjHLec8e
        NETLIFY_SITE_ID: 8bbd06df-7186-4424-aeb3-477eccbf41d7
          #NETLIFY_DEPLOY_TO_PROD: true
          #build_command: CI=false npm run build
      run: netlify deploy --prod

